version: '3.8'
services:
  # FastAPI application service
  bakerycake-app:
    container_name: bakerycake-app
    image: bakerycake-app:latest
    hostname: bakerycake-app
    ports:
      - "8500:8500"
    env_file:
      - .env
    depends_on:
      bakerycake-app-db:
        condition: service_healthy
    networks:
      - bakerycake-app

  # MySQL database service
  bakerycake-app-db:
    container_name: bakerycake-app-db
    image: mysql:latest
    hostname: bakerycake-app-db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bakerycake-app
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql:

networks:
  bakerycake-app: