version: '3.8'
services:
  # kalo connect database railway
  bakerytst-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /app
    
#   ## kalo pake mysql di container
#   bakerytst-app:
#     container_name: bakerytst-app
#     image: bakerytst-app:latest
#     hostname: bakerytst-app
#     ports:
#       - "8080:8080"
#     env_file:
#       - .env
#     depends_on:
#       bakerytst-app-db:
#         condition: service_healthy
#     networks:
#       - bakerytst-app

# #   # MySQL database service
#   bakerytst-app-db:
#     container_name: bakerytst-app-db
#     image: mysql:latest
#     hostname: bakerytst-app-db
#     env_file:
#       - .env
#     ports:
#       - "3308:3306"
#     volumes:
#       - ./mysql:/var/lib/mysql
#       - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks:
#       - bakerytst-app
#     restart: always
#     healthcheck:
#       test: mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD}
#       interval: 5s
#       timeout: 5s
#       retries: 20

# volumes:
#   mysql:

# networks:
#   bakerytst-app: